
build:
	./node_modules/.bin/webpack

run:
	./node_modules/.bin/webpack serve --env dev --no-color

test:
	echo Not implemented.


run-dist:
	npm install --no-save http-server
	./node_modules/.bin/http-server dist -p 32016 
